### ISSUE TITLE
Missing packets

### ISSUE THREAD

**Issue by pgwiazda** [QXIP/captagent-docker#3]
Hi,
I'm new here, and it is my first issue.

We are trying your solution (HOMER5 with qxip/CaptAgent6-docker) with our VoIP/IMS platform.
We put CaptAgent at mirroring flows between SBC---CSCF,  CSCF---AS.

But we occurred some difference between tcpdump from this flows and what we can see at Homer5 web. We have some packet loss

File tcpdump_flow.jpg it is some capture from tcpdump
![tcpdump_flow](https://cloud.githubusercontent.com/assets/17449639/13285383/9718c604-dafa-11e5-863b-02fe63b3eb05.JPG)

File Homer_view_calls.jpg it is capture from web for transaction CALLS
![homer_view_calls](https://cloud.githubusercontent.com/assets/17449639/13285381/97153016-dafa-11e5-8bd4-a23951528b88.JPG)

File Homer_view_registrations.jpg it is capture from web for transaction REGISTRATIONS
![homer_view_registrations](https://cloud.githubusercontent.com/assets/17449639/13285382/9716d66e-dafa-11e5-817f-6d8e03e1f79f.JPG)

As You can see , for example, we lost:
INVITE message from 11:33:30.621234
200 OK response from 11:33:30.613970 
REGISTER message from 11:33:30.639735

What could be the cause? 
Problem with captagent? Configuration?
What we should check?

Regards,
Przemek

**Comment by lmangani** [comment]
Hi @pgwiazda I assume the size of your INVITE and 200 OK is quite large and/or larger than MTU? Are you delivering via UDP or TCP to the collector? Please check the docker-homer console for Kamailio messages to see if those are being received and dropped to begin troubleshooting the problem, if unsure sniff on the HEP port to see if INVITES and other missing methods are being delivered.

**Comment by themicster** [comment]
I'm having the same problem. I'm using UDP for collection.

**Comment by lmangani** [comment]
Please try the latest build (or confirm if you are already on 6.1)

**Comment by themicster** [comment]
I've changed to another image now, but I did confirm that it was 6.1.

**Comment by lmangani** [comment]
mind to share the image if it solves the issue?

**Comment by themicster** [comment]
Ask @dougbtv, he got it going for me.

**Comment by dougbtv** [comment]
Just an FYI that the micster is a friend of mine, I got him running with the changes that I submitted in my PR (#5), so, that's all up-to-date with what I know. I'd love to replicate the issue, but.... There we have it.
