### ISSUE TITLE
Doesn't replace capture password in run.sh file

### ISSUE THREAD

**Issue by netaskd** [QXIP/captagent-docker#8]
In string +95 captagent-docker/run.sh doesn't replace "myHep" password, 'cause in original file $PATH_CAPTAGENT_TRANSPORT_XML it seems like "myhep".
My suggestion (I've added /i - ignore alphabetic case distinctions):
perl -p -i -e "s/myHep/$CAPTURE_PASSWORD/i" $PATH_CAPTAGENT_TRANSPORT_XML

**Comment by lmangani** [comment]
Thanks for catching this! Fixed in https://github.com/QXIP/captagent-docker/commit/71b0a25d5c2ee6d3d2b34f99b1e45a2ddc58d329
